-- +goose Up
-- +goose StatementBegin
CREATE TABLE print_configs (
    id BIGINT PRIMARY KEY PRIMARY KEY generated BY DEFAULT AS identity,
    technology VARCHAR(55) NOT NULL,
    material  VARCHAR(55) NOT NULL,
    color  VARCHAR(55) NOT NULL,
    quantity  VARCHAR(55) NOT NULL,
    file_id  VARCHAR(55) NOT NULL,
    user_id BIGINT NOT NULL,
    file_volume FLOAT NOT NULL,
    inserted_at TIMESTAMP(0) NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS print_configs;
-- +goose StatementEnd
