// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FileUpload() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex items-center justify-center h-full w-full flex-col gap-4\"><label for=\"dropzone-file\" class=\"flex flex-col items-center justify-center w-full border\n\t\tborder-dashed rounded-lg cursor-pointer h-full\n\t\tborder-gray-300 bg-blue-50/20 hover:bg-blue-50/60\" id=\"file-upload-container\"><div id=\"dropzone-label\" class=\"flex flex-col items-center justify-center pt-5 pb-6\"><div class=\"flex flex-col items-center gap-2 file-spinner\" id=\"file-spinner\"><span class=\"daisy-loading daisy-loading-infinity daisy-loading-lg\"></span> <span class=\"font-semibold text-gray-600 text-sm\">Uploading ...</span></div><svg class=\"w-8 h-8 mb-4 text-gray-500 to-hide\" aria-hidden=\"true\" fill=\"none\" viewBox=\"0 0 20 16\"><path stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2\"></path></svg><p class=\"mb-2 text-sm text-gray-800 text-center to-hide\" id=\"file-text\"><span class=\"font-semibold\">Click to upload</span><br>or drag & drop your STL Files here</p><p class=\"text-xs text-gray-500 to-hide\">STL Files</p></div><input hx-post=\"/file\" hx-on::before-request=\"beforeUploadFile(event)\" hx-encoding=\"multipart/form-data\" hx-trigger=\"change\" hx-indicator=\"#dropzone-label\" name=\"file\" accept=\".stl\" id=\"dropzone-file\" type=\"file\" class=\"hidden\"></label></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
