-- +goose Up
-- +goose StatementBegin

drop table if exists cart;
create table carts (
  id bigint primary key generated by default as identity,
  user_id bigint not null,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

drop table if exists cart_order;
create table cart_orders (
  cart_id bigint not null,
  order_id bigint not null,
  primary key(cart_id, order_id)
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table cart;
-- +goose StatementEnd
