-- +goose Up
-- +goose StatementBegin
create extension if not exists citext;

create table cart (
  id bigint primary key generated by default as identity,
  user_id bigint not null,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

create table cart_order (
  cart_id bigint not null,
  order_id bigint not null,
  primary key(cart_id, order_id)
);

-- rename transaction to orders
drop table transactions;
CREATE TABLE orders (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    inserted_at TIMESTAMP(0) NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    build_time BIGINT NOT NULL,
    quantity VARCHAR(255) NOT NULL,
    price FLOAT8 NOT NULL,
    phone VARCHAR(255) NOT NULL,
    payment_complete BOOLEAN NOT NULL,
    status VARCHAR(255) NOT NULL,

    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_file FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table cart;
-- +goose StatementEnd
