-- +goose Up
-- +goose StatementBegin
DROP TABLE if exists transaction_orders;
DROP TABLE if exists transactions;

CREATE TABLE transactions (
  id bigint primary key generated by default as identity,
  user_id bigint NOT NULL,
  payment_status varchar(255) NOT NULL,
  checkout_request_id varchar(255) NOT NULL,
  inserted_at timestamp(0) not null default (now() at time zone 'utc'),
  updated_at timestamp(0) not null default (now() at time zone 'utc'),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE transaction_orders (
  transaction_id bigint NOT NULL,
  order_id bigint NOT NULL,
  PRIMARY KEY(transaction_id, order_id),

  FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE transactions;
DROP TABLE transaction_orders;
-- +goose StatementEnd
